credentials:
  usernames:
    fede6590:
      email: fferreyra@teco.com.ar
      name: Federico Ferreyra
      password: $2b$12$vCAwoVz8AZ16XTzIArOFfONkkH9Rk8OQVgaupDdNDAFFKHx7MU.0O
    guest:
      email: guest@gmail.com
      name: Guest
      password: guest
cookie:
  expiry_days: 0
  key: some_signature_key # Must be string
  name: template_cookie
preauthorized:
  emails:
  - fferreyra@teco.com.ar
